import React from "react";

const Disclaimer = () => (
  <div className="container py-12 max-w-2xl mx-auto">
    <h1 className="text-3xl md:text-5xl font-bold mb-6 text-center bg-clip-text text-transparent bg-gradient-to-r from-primary to-primary/60" style={{ fontSize: '2.4rem' }}>
      Disclaimer
    </h1>
    <p className="text-sm text-muted-foreground mb-4 text-center">Last Updated: May 2025</p>
    <p className="mb-6 text-base text-foreground text-center">
      GitPeek is an AI-powered tool designed to help users analyze GitHub profiles, repositories, and coding behavior for educational, professional, or team collaboration purposes.
    </p>
    <div className="bg-background/60 border border-border/50 rounded-lg p-6 shadow-md">
      <p className="mb-4 font-semibold text-primary">By using GitPeek, you acknowledge that:</p>
      <ul className="list-disc pl-6 space-y-3 text-base text-muted-foreground">
        <li>All summaries, suggestions, or insights are generated by AI models based on publicly available GitHub data or user input.</li>
        <li>The platform does not guarantee the accuracy, recency, or correctness of any insights or profiles generated.</li>
        <li>GitPeek is not affiliated with GitHub Inc. or any of the developers whose repositories may be analyzed.</li>
        <li>Users are responsible for verifying AI-generated content before using it for hiring, evaluation, or decision-making.</li>
      </ul>
    </div>
  </div>
);

export default Disclaimer; 