import React from "react";

const TermsOfUse = () => (
  <div className="container py-12 max-w-2xl mx-auto">
    <h1
      className="text-center font-bold mb-6 bg-clip-text text-transparent bg-gradient-to-r from-primary to-primary/60"
      style={{ fontSize: '2.4rem', lineHeight: 1.1 }}
    >
      TERMS OF USE
    </h1>
    <p className="text-sm text-muted-foreground mb-4 text-center">Last Updated: May 2025</p>
    <div className="bg-background/60 border border-border/50 rounded-lg p-6 shadow-md mb-6">
      <p className="mb-4 text-base text-foreground">
        These Terms govern your use of GitPeek. By accessing the platform, you accept these conditions in full.
      </p>
      <h2 className="font-semibold text-primary mb-2 mt-4">4.1 Eligibility</h2>
      <p className="mb-4 text-base text-muted-foreground">You must be at least 13 years old (or the minimum age in your jurisdiction) to use GitPeek.</p>
      <h2 className="font-semibold text-primary mb-2 mt-4">4.2 User License</h2>
      <p className="mb-2 text-base text-foreground">We grant you a non-exclusive, revocable, and limited license to use GitPeek for lawful, personal, or professional purposes, provided that you:</p>
      <ul className="list-disc pl-6 space-y-2 text-base text-muted-foreground mb-4">
        <li>Do not resell, distribute, or commercialize AI outputs without permission.</li>
        <li>Do not exploit any bugs or security vulnerabilities.</li>
        <li>Adhere to GitHub's and GitPeek's acceptable use standards.</li>
      </ul>
      <h2 className="font-semibold text-primary mb-2 mt-4">4.3 Intellectual Property</h2>
      <ul className="list-disc pl-6 space-y-2 text-base text-muted-foreground mb-4">
        <li>All original code, models, UI/UX designs, branding, and logic are the property of GitPeek or its licensors.</li>
        <li>GitHub repositories and metadata belong to their respective owners and are shown under fair-use interpretation of public APIs.</li>
      </ul>
      <h2 className="font-semibold text-primary mb-2 mt-4">4.4 Platform Outputs</h2>
      <p className="mb-4 text-base text-foreground">Any profiles, summaries, or suggestions produced by GitPeek are generated by AI and may reflect algorithmic interpretations. They are intended for informational purposes only and should not be used as the sole basis for employment, recruitment, or academic evaluation.</p>
      <h2 className="font-semibold text-primary mb-2 mt-4">4.5 Limitation of Liability</h2>
      <ul className="list-disc pl-6 space-y-2 text-base text-muted-foreground mb-4">
        <li>Losses or damages resulting from reliance on AI-generated profiles.</li>
        <li>Inaccurate or outdated information about third-party repositories or individuals.</li>
        <li>Technical failures, downtime, or data loss.</li>
      </ul>
      <h2 className="font-semibold text-primary mb-2 mt-4">4.6 Termination</h2>
      <p className="mb-4 text-base text-foreground">We may suspend or revoke access to GitPeek at any time, with or without notice, especially in cases of abuse, unauthorized access, or breach of these Terms.</p>
      <h2 className="font-semibold text-primary mb-2 mt-4">5. CHANGES TO THESE TERMS</h2>
      <p className="mb-4 text-base text-foreground">We may update these documents from time to time. Continued use of the platform after changes take effect constitutes acceptance of the revised terms.</p>
      <p className="mb-4 text-base text-foreground">We encourage you to periodically review this page.</p>
      <h2 className="font-semibold text-primary mb-2 mt-4">6. CONTACT</h2>
      <p className="text-base text-foreground">If you have questions, concerns, or data requests, contact us at:</p>
      <p className="text-base text-foreground">📧 Email: <a href="mailto:aditya.kemdarne@neuralarc.ai" className="underline">aditya.kemdarne@neuralarc.ai</a></p>
    </div>
  </div>
);

export default TermsOfUse; 